name: ludo
description: "ludo board game"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ^3.5.0
  flutter: ^3.24.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.21.0
  flame_audio: ^2.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/move.mp3
    - assets/audio/dice.mp3