name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # This workflow uses the latest stable version of the Dart SDK.
      # Specify other versions if needed. For Flutter projects, use 'flutter setup':
      - uses: subosito/flutter-action@v2 # Flutter setup

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      # Use 'flutter test' for Flutter projects instead of 'dart test'.
      - name: Run tests
        run: flutter test
